services:
  postgres:
    image: postgres:16-alpine
    container_name: pontoestagio_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mySuperSecurePassword
      POSTGRES_DB: pontoestagio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    name: pontoestagio_postgres_data
