services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pontoestagio_sql
    environment:
      SA_PASSWORD: "MyNewComplexPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
    name: pontoestagio_sqlserver_data
