//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoEstagio.Exceptions.ResourcesErrors {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PontoEstagio.Exceptions.ResourcesErrors.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atividade não encontrada..
        /// </summary>
        public static string ActivityNotFound {
            get {
                return ResourceManager.GetString("ActivityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Associação não encontrada ou já está inativa..
        /// </summary>
        public static string AssociationNotFoundOrInactive {
            get {
                return ResourceManager.GetString("AssociationNotFoundOrInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário já tem uma presença registrada para esta data..
        /// </summary>
        public static string AttendanceAlreadyExists {
            get {
                return ResourceManager.GetString("AttendanceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A presença deve ter pelo menos uma atividade vinculada a um projeto..
        /// </summary>
        public static string AttendanceMustHaveLinkedActivity {
            get {
                return ResourceManager.GetString("AttendanceMustHaveLinkedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Presença não encontrada..
        /// </summary>
        public static string AttendanceNotFound {
            get {
                return ResourceManager.GetString("AttendanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não pode remover a si mesmo deste projeto..
        /// </summary>
        public static string CannotRemoveSelfFromProject {
            get {
                return ResourceManager.GetString("CannotRemoveSelfFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O horário de check-in é obrigatório..
        /// </summary>
        public static string CheckInTimeIsRequired {
            get {
                return ResourceManager.GetString("CheckInTimeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O horário de check-in deve ser um horário válido..
        /// </summary>
        public static string CheckInTimeMustBeValid {
            get {
                return ResourceManager.GetString("CheckInTimeMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O horário de check-out deve ser posterior ao horário de check-in..
        /// </summary>
        public static string CheckOutMustBeLaterThanCheckIn {
            get {
                return ResourceManager.GetString("CheckOutMustBeLaterThanCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O horário de check-out é obrigatório..
        /// </summary>
        public static string CheckOutTimeIsRequired {
            get {
                return ResourceManager.GetString("CheckOutTimeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O horário de check-out deve ser um horário válido..
        /// </summary>
        public static string CheckOutTimeMustBeValid {
            get {
                return ResourceManager.GetString("CheckOutTimeMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ já cadastrado.
        /// </summary>
        public static string CnpjAlreadyExists {
            get {
                return ResourceManager.GetString("CnpjAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ não pode ser vazio..
        /// </summary>
        public static string CnpjCannotBeEmpty {
            get {
                return ResourceManager.GetString("CnpjCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ deve estar no formato XX.XXX.XXX/XXXX-XX..
        /// </summary>
        public static string Company_CNPJ_InvalidFormat {
            get {
                return ResourceManager.GetString("Company_CNPJ_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ é obrigatório..
        /// </summary>
        public static string Company_CNPJ_Required {
            get {
                return ResourceManager.GetString("Company_CNPJ_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formato de e-mail inválido..
        /// </summary>
        public static string Company_Email_Invalid {
            get {
                return ResourceManager.GetString("Company_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail é obrigatório..
        /// </summary>
        public static string Company_Email_Required {
            get {
                return ResourceManager.GetString("Company_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome da empresa deve ter no mínimo 3 caracteres..
        /// </summary>
        public static string Company_Name_MinLength {
            get {
                return ResourceManager.GetString("Company_Name_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome da empresa é obrigatório..
        /// </summary>
        public static string Company_Name_Required {
            get {
                return ResourceManager.GetString("Company_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Empresa não encontrada..
        /// </summary>
        public static string Company_NotFound {
            get {
                return ResourceManager.GetString("Company_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número de telefone deve estar no formato (XX) XXXX-XXXX ou (XX) XXXXX-XXXX..
        /// </summary>
        public static string Company_Phone_InvalidFormat {
            get {
                return ResourceManager.GetString("Company_Phone_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número de telefone é obrigatório..
        /// </summary>
        public static string Company_Phone_Required {
            get {
                return ResourceManager.GetString("Company_Phone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data não pode ser no futuro..
        /// </summary>
        public static string DateCannotBeInTheFuture {
            get {
                return ResourceManager.GetString("DateCannotBeInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data é obrigatória..
        /// </summary>
        public static string DateIsRequired {
            get {
                return ResourceManager.GetString("DateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email já está em uso..
        /// </summary>
        public static string EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email não pode estar vazio..
        /// </summary>
        public static string EmailCannotBeEmpty {
            get {
                return ResourceManager.GetString("EmailCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de término deve ser posterior à data de início..
        /// </summary>
        public static string EndDateMustBeLaterThanStartDate {
            get {
                return ResourceManager.GetString("EndDateMustBeLaterThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de registro de ponto não pode ser no futuro..
        /// </summary>
        public static string invalidAttendanceDate {
            get {
                return ResourceManager.GetString("invalidAttendanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID de presença não pode ser vazio..
        /// </summary>
        public static string invalidAttendanceId {
            get {
                return ResourceManager.GetString("invalidAttendanceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O horário de saída não pode ser anterior ao horário de entrada..
        /// </summary>
        public static string invalidCheckOutTime {
            get {
                return ResourceManager.GetString("invalidCheckOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formato de CNPJ inválido..
        /// </summary>
        public static string InvalidCnpjFormat {
            get {
                return ResourceManager.GetString("InvalidCnpjFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID da empresa não pode ser vazio..
        /// </summary>
        public static string InvalidCompanyId {
            get {
                return ResourceManager.GetString("InvalidCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formato do email é inválido..
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data não pode ser anterior ao dia de hoje..
        /// </summary>
        public static string invalidExpirationDate {
            get {
                return ResourceManager.GetString("invalidExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login inválido. Verifique seu email e senha..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha do usuário não pode ser vazia..
        /// </summary>
        public static string invalidPassword {
            get {
                return ResourceManager.GetString("invalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Período inválido. Use o formato &apos;yyyy-MM&apos;..
        /// </summary>
        public static string InvalidPeriodFormat {
            get {
                return ResourceManager.GetString("InvalidPeriodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID do projeto não pode ser vazio..
        /// </summary>
        public static string invalidProjectId {
            get {
                return ResourceManager.GetString("invalidProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do projeto não pode ser vazio..
        /// </summary>
        public static string invalidProjectName {
            get {
                return ResourceManager.GetString("invalidProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do projeto deve ter pelo menos 3 caracteres..
        /// </summary>
        public static string invalidProjectNameLength {
            get {
                return ResourceManager.GetString("invalidProjectNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O caminho do arquivo de comprovação não pode ser vazio..
        /// </summary>
        public static string invalidProofFilePath {
            get {
                return ResourceManager.GetString("invalidProofFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de registro da atividade não pode ser no futuro..
        /// </summary>
        public static string invalidRecordedAtDate {
            get {
                return ResourceManager.GetString("invalidRecordedAtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status inválido..
        /// </summary>
        public static string InvalidStatus {
            get {
                return ResourceManager.GetString("InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O token não pode ser vazio..
        /// </summary>
        public static string invalidToken {
            get {
                return ResourceManager.GetString("invalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor de TotalHours deve ser maior que 0..
        /// </summary>
        public static string invalidTotalHours {
            get {
                return ResourceManager.GetString("invalidTotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID do usuário não pode ser vazio..
        /// </summary>
        public static string invalidUserId {
            get {
                return ResourceManager.GetString("invalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do usuário não pode ser vazio..
        /// </summary>
        public static string invalidUserName {
            get {
                return ResourceManager.GetString("invalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de usuário inválido. Acesso negado..
        /// </summary>
        public static string InvalidUserType {
            get {
                return ResourceManager.GetString("InvalidUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de usuário inválido para listagem de atividades..
        /// </summary>
        public static string InvalidUserTypeForListing {
            get {
                return ResourceManager.GetString("InvalidUserTypeForListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome não pode ser vazio..
        /// </summary>
        public static string NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não pode estar vazia..
        /// </summary>
        public static string PasswordCannotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não pode estar vazia..
        /// </summary>
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter pelo menos uma letra minúscula..
        /// </summary>
        public static string PasswordMissingLowercase {
            get {
                return ResourceManager.GetString("PasswordMissingLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter pelo menos um número..
        /// </summary>
        public static string PasswordMissingNumber {
            get {
                return ResourceManager.GetString("PasswordMissingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter pelo menos um caractere especial..
        /// </summary>
        public static string PasswordMissingSpecialCharacter {
            get {
                return ResourceManager.GetString("PasswordMissingSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter pelo menos uma letra maiúscula..
        /// </summary>
        public static string PasswordMissingUppercase {
            get {
                return ResourceManager.GetString("PasswordMissingUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve ter pelo menos 8 caracteres..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do projeto é obrigatório..
        /// </summary>
        public static string ProjectNameRequired {
            get {
                return ResourceManager.GetString("ProjectNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Projeto não encontrado..
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de início deve ser hoje ou uma data futura..
        /// </summary>
        public static string StartDateMustBeTodayOrFuture {
            get {
                return ResourceManager.GetString("StartDateMustBeTodayOrFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O supervisor já está atribuído a este projeto..
        /// </summary>
        public static string SupervisorAlreadyAssignedToProject {
            get {
                return ResourceManager.GetString("SupervisorAlreadyAssignedToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Associação do supervisor não encontrada ou já está inativa..
        /// </summary>
        public static string SupervisorAssociationNotFound {
            get {
                return ResourceManager.GetString("SupervisorAssociationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O supervisor não existe ou não tem o tipo de usuário Supervisor..
        /// </summary>
        public static string SupervisorNotFoundOrNotSupervisor {
            get {
                return ResourceManager.GetString("SupervisorNotFoundOrNotSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário já está atribuído a este projeto..
        /// </summary>
        public static string UserAlreadyAssignedToProject {
            get {
                return ResourceManager.GetString("UserAlreadyAssignedToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário já tem um projeto em andamento e não pode ser atribuído a outro..
        /// </summary>
        public static string UserAlreadyHasOngoingProject {
            get {
                return ResourceManager.GetString("UserAlreadyHasOngoingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário está inativo..
        /// </summary>
        public static string UserNotActive {
            get {
                return ResourceManager.GetString("UserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário não é um adiministrador..
        /// </summary>
        public static string UserNotAdmin {
            get {
                return ResourceManager.GetString("UserNotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário não é um estagiário..
        /// </summary>
        public static string UserNotIntern {
            get {
                return ResourceManager.GetString("UserNotIntern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário não é um supervisor..
        /// </summary>
        public static string UserNotSupervisor {
            get {
                return ResourceManager.GetString("UserNotSupervisor", resourceCulture);
            }
        }
    }
}
