//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoEstagio.Exceptions.ResourcesErrors {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PontoEstagio.Exceptions.ResourcesErrors.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atividade não encontrada..
        /// </summary>
        public static string ActivityNotFound {
            get {
                return ResourceManager.GetString("ActivityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade é obrigatória..
        /// </summary>
        public static string Address_CityRequired {
            get {
                return ResourceManager.GetString("Address_CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro é obrigatório..
        /// </summary>
        public static string Address_DistrictRequired {
            get {
                return ResourceManager.GetString("Address_DistrictRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número é obrigatório..
        /// </summary>
        public static string Address_NumberRequired {
            get {
                return ResourceManager.GetString("Address_NumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estado é obrigatório..
        /// </summary>
        public static string Address_StateRequired {
            get {
                return ResourceManager.GetString("Address_StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rua é obrigatória..
        /// </summary>
        public static string Address_StreetRequired {
            get {
                return ResourceManager.GetString("Address_StreetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP deve conter 8 dígitos..
        /// </summary>
        public static string Address_ZipCodeInvalid {
            get {
                return ResourceManager.GetString("Address_ZipCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP é obrigatório..
        /// </summary>
        public static string Address_ZipCodeRequired {
            get {
                return ResourceManager.GetString("Address_ZipCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O endereço é obrigatório..
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este código já foi utilizado..
        /// </summary>
        public static string AlreadyUsed {
            get {
                return ResourceManager.GetString("AlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Associação não encontrada ou já está inativa..
        /// </summary>
        public static string AssociationNotFoundOrInactive {
            get {
                return ResourceManager.GetString("AssociationNotFoundOrInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário já tem uma presença registrada para esta data..
        /// </summary>
        public static string AttendanceAlreadyExists {
            get {
                return ResourceManager.GetString("AttendanceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID da presença é obrigatório..
        /// </summary>
        public static string AttendanceIdIsRequired {
            get {
                return ResourceManager.GetString("AttendanceIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A presença deve ter pelo menos uma atividade vinculada a um projeto..
        /// </summary>
        public static string AttendanceMustHaveLinkedActivity {
            get {
                return ResourceManager.GetString("AttendanceMustHaveLinkedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Presença não encontrada..
        /// </summary>
        public static string AttendanceNotFound {
            get {
                return ResourceManager.GetString("AttendanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não pode remover a si mesmo deste projeto..
        /// </summary>
        public static string CannotRemoveSelfFromProject {
            get {
                return ResourceManager.GetString("CannotRemoveSelfFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O horário de check-in é obrigatório..
        /// </summary>
        public static string CheckInTimeIsRequired {
            get {
                return ResourceManager.GetString("CheckInTimeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O horário de check-in deve ser um horário válido..
        /// </summary>
        public static string CheckInTimeMustBeValid {
            get {
                return ResourceManager.GetString("CheckInTimeMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O horário de check-out deve ser posterior ao horário de check-in..
        /// </summary>
        public static string CheckOutMustBeLaterThanCheckIn {
            get {
                return ResourceManager.GetString("CheckOutMustBeLaterThanCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O horário de check-out é obrigatório..
        /// </summary>
        public static string CheckOutTimeIsRequired {
            get {
                return ResourceManager.GetString("CheckOutTimeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O horário de check-out deve ser um horário válido..
        /// </summary>
        public static string CheckOutTimeMustBeValid {
            get {
                return ResourceManager.GetString("CheckOutTimeMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A cidade é obrigatória..
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ já cadastrado.
        /// </summary>
        public static string CnpjAlreadyExists {
            get {
                return ResourceManager.GetString("CnpjAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ já registrado..
        /// </summary>
        public static string CNPJAlreadyRegistered {
            get {
                return ResourceManager.GetString("CNPJAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ não pode ser vazio..
        /// </summary>
        public static string CnpjCannotBeEmpty {
            get {
                return ResourceManager.GetString("CnpjCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de recuperação é obrigatório..
        /// </summary>
        public static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ deve estar no formato XX.XXX.XXX/XXXX-XX..
        /// </summary>
        public static string Company_CNPJ_InvalidFormat {
            get {
                return ResourceManager.GetString("Company_CNPJ_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ é obrigatório..
        /// </summary>
        public static string Company_CNPJ_Required {
            get {
                return ResourceManager.GetString("Company_CNPJ_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formato de e-mail inválido..
        /// </summary>
        public static string Company_Email_Invalid {
            get {
                return ResourceManager.GetString("Company_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail é obrigatório..
        /// </summary>
        public static string Company_Email_Required {
            get {
                return ResourceManager.GetString("Company_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome da empresa deve ter no mínimo 3 caracteres..
        /// </summary>
        public static string Company_Name_MinLength {
            get {
                return ResourceManager.GetString("Company_Name_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome da empresa é obrigatório..
        /// </summary>
        public static string Company_Name_Required {
            get {
                return ResourceManager.GetString("Company_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Empresa não encontrada..
        /// </summary>
        public static string Company_NotFound {
            get {
                return ResourceManager.GetString("Company_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número de telefone deve estar no formato (XX) XXXX-XXXX ou (XX) XXXXX-XXXX..
        /// </summary>
        public static string Company_Phone_InvalidFormat {
            get {
                return ResourceManager.GetString("Company_Phone_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número de telefone é obrigatório..
        /// </summary>
        public static string Company_Phone_Required {
            get {
                return ResourceManager.GetString("Company_Phone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do curso deve ter pelo menos 3 caracteres..
        /// </summary>
        public static string CourseNameMinLength {
            get {
                return ResourceManager.GetString("CourseNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do curso é obrigatório..
        /// </summary>
        public static string CourseNameRequired {
            get {
                return ResourceManager.GetString("CourseNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Curso não encontrado..
        /// </summary>
        public static string CourseNotFound {
            get {
                return ResourceManager.GetString("CourseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data não pode ser no futuro..
        /// </summary>
        public static string DateCannotBeInTheFuture {
            get {
                return ResourceManager.GetString("DateCannotBeInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data é obrigatória..
        /// </summary>
        public static string DateIsRequired {
            get {
                return ResourceManager.GetString("DateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email já está em uso..
        /// </summary>
        public static string EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email já registrado..
        /// </summary>
        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email não pode estar vazio..
        /// </summary>
        public static string EmailCannotBeEmpty {
            get {
                return ResourceManager.GetString("EmailCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Template de e-mail para redefinição de senha não encontrado..
        /// </summary>
        public static string EmailTemplatePasswordResetNotFound {
            get {
                return ResourceManager.GetString("EmailTemplatePasswordResetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de término deve ser posterior à data de início..
        /// </summary>
        public static string EndDateMustBeLaterThanStartDate {
            get {
                return ResourceManager.GetString("EndDateMustBeLaterThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de expiração deve ser futura..
        /// </summary>
        public static string ExpirationInPast {
            get {
                return ResourceManager.GetString("ExpirationInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este código de recuperação está expirado..
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O comprovante não pode exceder 5MB..
        /// </summary>
        public static string FileTooLarge {
            get {
                return ResourceManager.GetString("FileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O aluno já está vinculado a um projeto de estágio com status ativo..
        /// </summary>
        public static string InternAlreadyAssignedToActiveProject {
            get {
                return ResourceManager.GetString("InternAlreadyAssignedToActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A frequência só pode ser registrada para a data atual..
        /// </summary>
        public static string InvalidAttendanceDate {
            get {
                return ResourceManager.GetString("InvalidAttendanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID de presença não pode ser vazio..
        /// </summary>
        public static string InvalidAttendanceId {
            get {
                return ResourceManager.GetString("InvalidAttendanceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O comprovante deve estar em formato Base64 válido..
        /// </summary>
        public static string InvalidBase64 {
            get {
                return ResourceManager.GetString("InvalidBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O horário de saída não pode ser anterior ao horário de entrada..
        /// </summary>
        public static string InvalidCheckOutTime {
            get {
                return ResourceManager.GetString("InvalidCheckOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formato de CNPJ inválido..
        /// </summary>
        public static string InvalidCnpjFormat {
            get {
                return ResourceManager.GetString("InvalidCnpjFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID da empresa não pode ser vazio..
        /// </summary>
        public static string InvalidCompanyId {
            get {
                return ResourceManager.GetString("InvalidCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuários do tipo Estagiário ou Coordenador devem estar vinculados a um curso..
        /// </summary>
        public static string InvalidCourseIdForUserType {
            get {
                return ResourceManager.GetString("InvalidCourseIdForUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do curso é inválido ou está em branco..
        /// </summary>
        public static string InvalidCourseName {
            get {
                return ResourceManager.GetString("InvalidCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formato do email é inválido..
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data não pode ser anterior ao dia de hoje..
        /// </summary>
        public static string invalidExpirationDate {
            get {
                return ResourceManager.GetString("invalidExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login inválido. Verifique seu email e senha..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha do usuário não pode ser vazia..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Período inválido. Use o formato &apos;yyyy-MM&apos;..
        /// </summary>
        public static string InvalidPeriodFormat {
            get {
                return ResourceManager.GetString("InvalidPeriodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Classificação de estágio inválida..
        /// </summary>
        public static string InvalidProjectClassification {
            get {
                return ResourceManager.GetString("InvalidProjectClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID do projeto não pode ser vazio..
        /// </summary>
        public static string InvalidProjectId {
            get {
                return ResourceManager.GetString("InvalidProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do projeto não pode ser vazio..
        /// </summary>
        public static string InvalidProjectName {
            get {
                return ResourceManager.GetString("InvalidProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do projeto deve ter pelo menos 3 caracteres..
        /// </summary>
        public static string InvalidProjectNameLength {
            get {
                return ResourceManager.GetString("InvalidProjectNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O caminho do arquivo de comprovação não pode ser vazio..
        /// </summary>
        public static string InvalidProofFilePath {
            get {
                return ResourceManager.GetString("InvalidProofFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A imagem de comprovação é inválida..
        /// </summary>
        public static string InvalidProofImage {
            get {
                return ResourceManager.GetString("InvalidProofImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de registro da atividade não pode ser no futuro..
        /// </summary>
        public static string invalidRecordedAtDate {
            get {
                return ResourceManager.GetString("invalidRecordedAtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A matrícula é obrigatória..
        /// </summary>
        public static string InvalidRegistration {
            get {
                return ResourceManager.GetString("InvalidRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status inválido..
        /// </summary>
        public static string InvalidStatus {
            get {
                return ResourceManager.GetString("InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O token não pode ser vazio..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor de TotalHours deve ser maior que 0..
        /// </summary>
        public static string InvalidTotalHours {
            get {
                return ResourceManager.GetString("InvalidTotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo de universidade é obrigatório..
        /// </summary>
        public static string InvalidUniversityId {
            get {
                return ResourceManager.GetString("InvalidUniversityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário inválido..
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID do usuário não pode ser vazio..
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do usuário não pode ser vazio..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de usuário inválido. Acesso negado..
        /// </summary>
        public static string InvalidUserType {
            get {
                return ResourceManager.GetString("InvalidUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de usuário inválido para listagem de atividades..
        /// </summary>
        public static string InvalidUserTypeForListing {
            get {
                return ResourceManager.GetString("InvalidUserTypeForListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A carga horária deve ser maior que zero..
        /// </summary>
        public static string InvalidWorkloadHours {
            get {
                return ResourceManager.GetString("InvalidWorkloadHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Representante legal não encontrado para esta empresa..
        /// </summary>
        public static string LegalRepresentativeNotFound {
            get {
                return ResourceManager.GetString("LegalRepresentativeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome não pode ser vazio..
        /// </summary>
        public static string NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número é obrigatório..
        /// </summary>
        public static string NumberRequired {
            get {
                return ResourceManager.GetString("NumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não pode estar vazia..
        /// </summary>
        public static string PasswordCannotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não pode estar vazia..
        /// </summary>
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter pelo menos uma letra minúscula..
        /// </summary>
        public static string PasswordMissingLowercase {
            get {
                return ResourceManager.GetString("PasswordMissingLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter pelo menos um número..
        /// </summary>
        public static string PasswordMissingNumber {
            get {
                return ResourceManager.GetString("PasswordMissingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter pelo menos um caractere especial..
        /// </summary>
        public static string PasswordMissingSpecialCharacter {
            get {
                return ResourceManager.GetString("PasswordMissingSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter pelo menos uma letra maiúscula..
        /// </summary>
        public static string PasswordMissingUppercase {
            get {
                return ResourceManager.GetString("PasswordMissingUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de recuperação inválido ou expirado..
        /// </summary>
        public static string PasswordRecovery_Code_Invalid {
            get {
                return ResourceManager.GetString("PasswordRecovery_Code_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve ter pelo menos 8 caracteres..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de telefone é obrigatório..
        /// </summary>
        public static string PhoneIsRequired {
            get {
                return ResourceManager.GetString("PhoneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de telefone deve ter no máximo 20 caracteres..
        /// </summary>
        public static string PhoneMaxLength {
            get {
                return ResourceManager.GetString("PhoneMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do projeto é obrigatório..
        /// </summary>
        public static string ProjectNameRequired {
            get {
                return ResourceManager.GetString("ProjectNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O cadastro de estágio ainda não foi aprovado pelo coordenador..
        /// </summary>
        public static string ProjectNotApprovedYet {
            get {
                return ResourceManager.GetString("ProjectNotApprovedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Projeto não encontrado..
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um usuário cadastrado com esta matrícula..
        /// </summary>
        public static string RegistrationAlreadyInUse {
            get {
                return ResourceManager.GetString("RegistrationAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Representante legal informado já está cadastrado no sistema..
        /// </summary>
        public static string RepresentativeAlreadyExists {
            get {
                return ResourceManager.GetString("RepresentativeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF deve conter exatamente 11 dígitos numéricos..
        /// </summary>
        public static string RepresentativeCpfInvalid {
            get {
                return ResourceManager.GetString("RepresentativeCpfInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF do representante legal é obrigatório..
        /// </summary>
        public static string RepresentativeCpfRequired {
            get {
                return ResourceManager.GetString("RepresentativeCpfRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail informado não é válido..
        /// </summary>
        public static string RepresentativeEmailInvalid {
            get {
                return ResourceManager.GetString("RepresentativeEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail é obrigatório..
        /// </summary>
        public static string RepresentativeEmailRequired {
            get {
                return ResourceManager.GetString("RepresentativeEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do representante legal é obrigatório..
        /// </summary>
        public static string RepresentativeNameRequired {
            get {
                return ResourceManager.GetString("RepresentativeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O cargo/função do representante legal é obrigatório..
        /// </summary>
        public static string RepresentativePositionRequired {
            get {
                return ResourceManager.GetString("RepresentativePositionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O cargo do representante não pode exceder 100 caracteres..
        /// </summary>
        public static string RepresentativePositionTooLong {
            get {
                return ResourceManager.GetString("RepresentativePositionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código deve ter exatamente 6 caracteres..
        /// </summary>
        public static string ResetPassword_Code_Length {
            get {
                return ResourceManager.GetString("ResetPassword_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código de recuperação é obrigatório..
        /// </summary>
        public static string ResetPassword_Code_Required {
            get {
                return ResourceManager.GetString("ResetPassword_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de início deve ser hoje ou uma data futura..
        /// </summary>
        public static string StartDateMustBeTodayOrFuture {
            get {
                return ResourceManager.GetString("StartDateMustBeTodayOrFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O estado deve conter 2 letras (UF)..
        /// </summary>
        public static string StateInvalidLength {
            get {
                return ResourceManager.GetString("StateInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O estado é obrigatório..
        /// </summary>
        public static string StateRequired {
            get {
                return ResourceManager.GetString("StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A rua é obrigatória..
        /// </summary>
        public static string StreetRequired {
            get {
                return ResourceManager.GetString("StreetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O supervisor já está atribuído a este projeto..
        /// </summary>
        public static string SupervisorAlreadyAssignedToProject {
            get {
                return ResourceManager.GetString("SupervisorAlreadyAssignedToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Associação do supervisor não encontrada ou já está inativa..
        /// </summary>
        public static string SupervisorAssociationNotFound {
            get {
                return ResourceManager.GetString("SupervisorAssociationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O supervisor já está atribuído ao número máximo de 10 projetos em andamento..
        /// </summary>
        public static string SupervisorMaxProjectsExceeded {
            get {
                return ResourceManager.GetString("SupervisorMaxProjectsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O supervisor não existe ou não tem o tipo de usuário Supervisor..
        /// </summary>
        public static string SupervisorNotFoundOrNotSupervisor {
            get {
                return ResourceManager.GetString("SupervisorNotFoundOrNotSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sigla da universidade é obrigatória..
        /// </summary>
        public static string University_AcronymRequired {
            get {
                return ResourceManager.GetString("University_AcronymRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome da universidade é obrigatório..
        /// </summary>
        public static string University_NameRequired {
            get {
                return ResourceManager.GetString("University_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone da universidade é obrigatório..
        /// </summary>
        public static string University_PhoneRequired {
            get {
                return ResourceManager.GetString("University_PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID da universidade é obrigatório..
        /// </summary>
        public static string UniversityIdRequired {
            get {
                return ResourceManager.GetString("UniversityIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário já está atribuído a este projeto..
        /// </summary>
        public static string UserAlreadyAssignedToProject {
            get {
                return ResourceManager.GetString("UserAlreadyAssignedToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário já tem um projeto em andamento e não pode ser atribuído a outro..
        /// </summary>
        public static string UserAlreadyHasOngoingProject {
            get {
                return ResourceManager.GetString("UserAlreadyHasOngoingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário não possui cadastro de estágio em andamento..
        /// </summary>
        public static string UserHasNoOngoingProject {
            get {
                return ResourceManager.GetString("UserHasNoOngoingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário está inativo..
        /// </summary>
        public static string UserNotActive {
            get {
                return ResourceManager.GetString("UserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário não é um adiministrador..
        /// </summary>
        public static string UserNotAdmin {
            get {
                return ResourceManager.GetString("UserNotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário não é um estagiário..
        /// </summary>
        public static string UserNotIntern {
            get {
                return ResourceManager.GetString("UserNotIntern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário não é um supervisor..
        /// </summary>
        public static string UserNotSupervisor {
            get {
                return ResourceManager.GetString("UserNotSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A carga horária deve ser maior que zero..
        /// </summary>
        public static string WorkloadHoursGreaterThanZero {
            get {
                return ResourceManager.GetString("WorkloadHoursGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A carga horária é obrigatória..
        /// </summary>
        public static string WorkloadHoursRequired {
            get {
                return ResourceManager.GetString("WorkloadHoursRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CEP deve conter exatamente 8 dígitos..
        /// </summary>
        public static string ZipCodeInvalid {
            get {
                return ResourceManager.GetString("ZipCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CEP é obrigatório..
        /// </summary>
        public static string ZipCodeRequired {
            get {
                return ResourceManager.GetString("ZipCodeRequired", resourceCulture);
            }
        }
    }
}
