name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Listar estrutura de arquivos (para debug)
        run: ls -R

      - name: Restaurar dependências
        run: |
          cd Backend
          dotnet restore

      - name: Compilar projeto
        run: |
          cd Backend
          dotnet build --configuration Release --no-restore

      - name: Rodar testes
        run: |
          cd Backend
          dotnet test --configuration Release --no-build --no-restore