name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore Backend/PontoEstagio.sln

      - name: Compilar projeto
        run: dotnet build Backend/PontoEstagio.sln --configuration Release --no-restore

      - name: Rodar testes
        run: dotnet test Backend/PontoEstagio.sln --configuration Release --no-build --no-restore
