name: CI/CD

on:
  push:
    branches:
      - main
      - devel
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore Backend/PontoEstagio.sln

      - name: Build solution
        run: dotnet build Backend/PontoEstagio.sln --configuration Release --no-restore

      - name: Run tests
        env:
          ASPNETCORE_ENVIRONMENT: Test
        run: dotnet test Backend/PontoEstagio.sln --configuration Release --no-build --no-restore

      - name: Publish API project
        run: dotnet publish Backend/src/PontoEstagio.API/PontoEstagio.API.csproj -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C575C30A528C4A90BE610C3469E11BD3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_695F7EE572704430A15B8122DBDB694A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9678EB10290E4363A0DCA41C68F42E22 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "registra-web"
          slot-name: "Production"
          package: .
